#!/bin/bash

# script/vagrant: Setup vagrant environment after cloning

set -e
set -o errexit
set -o errtrace

cd $(dirname $0)/..

ping_result="$(ping -c 2 8.8.4.4 2>&1)"
if [[ $ping_result != *bytes?from* ]]; then
    echo "Network connection unavailable. Try again later."
    exit 1
fi

ln -s /vagrant $HOME/website

source /vagrant/script/settings

echo "gem: --no-ri --no-rdoc" > /home/vagrant/.gemrc

/vagrant/script/bootstrap

#configure work folder
if [ ! -d $HOME_DIR ]
then
    ln -s /vagrant $HOME_DIR
    cd $HOME_DIR
fi

echo "cd ${HOME_DIR}" | sudo tee -a /home/vagrant/.bash_profile

#configure git
git config --global push.default simple
git config --global core.autocrlf input

#update editor configs
cp /vagrant/.inputrc /home/vagrant
cp /vagrant/.vimrc /home/vagrant